server:
  port: 8080
spring:
  docker:
    compose:
      enabled: true
      file: dev-docker-compose.yaml
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
logging:
  level:
    ROOT: INFO
    ru.iql.banking: DEBUG
    org.springframework:
      orm.jpa: DEBUG
      transaction: DEBUG

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
