--liquibase formatted sql

--changeset nikita.ryadnov:1
CREATE SCHEMA IF NOT EXISTS unibell
--changeset nikita.ryadnov:2
    CREATE TABLE IF NOT EXISTS unibell.clients
    (
        id   BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        name VARCHAR(255) UNIQUE NOT NULL
    )
--changeset nikita.ryadnov:3
    CREATE TABLE IF NOT EXISTS unibell.phones
    (
        id     BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        number VARCHAR(255) UNIQUE NOT NULL,
        client_id BIGINT NOT NULL REFERENCES unibell.clients(id)
    )
--changeset nikita.ryadnov:4
    CREATE TABLE IF NOT EXISTS unibell.emails
    (
        id     BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        name VARCHAR(255) UNIQUE NOT NULL,
        client_id BIGINT NOT NULL REFERENCES unibell.clients(id)
    )
